name: amidoneyet
description: A todo app with a twist.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  delayed_display: ^2.0.0
  flutter_markdown: ^0.7.1
  flutter_sticky_header: ^0.6.5
  flutter:
    sdk: flutter
  implicitly_animated_reorderable_list_2: ^0.6.0
  path_provider: ^2.1.3
  percent_indicator: ^4.2.3
  sembast: ^3.7.1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
